version: '3'
services:
  app:
    container_name: sih_app
    hostname: sih_app
    build: .
    command: ''
    restart: always
    volumes:
      - ./src:/home/node/app/src
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - mongo
      - redis
    links:
      - mongo:mongo
      - redis:redis
    networks:
      - network

  mongo:
    container_name: sih_mongo
    hostname: sih_mongo
    image: mongo:3.6
    restart: always
    ports:
      - 3003:27017
    networks:
      - network

  redis:
    container_name: sih_redis
    hostname: sih_redis
    image: redis:alpine
    restart: always
    networks:
      - network

  redis_cmdr:
    container_name: sih_redis_cmdr
    hostname: sih_redis_cmdr
    image: tenstartups/redis-commander
    command: --redis-host redis --redis-port 6379
    links:
      - redis:redis
    ports:
      - 3002:8081
    networks:
      - network

networks:
  network:
      driver: bridge
